version: '3.7'

services:
  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
      - 25:25
      - 143:143
      - 587:587
      - 993:993
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_POP3=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=self-signed
      - ENABLE_SPAMASSASSIN=0
      - POSTFIX_INET_PROTOCOLS=ipv4
      - PERMIT_DOCKER=network
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs: